### PR TITLE
Update schemas for DOS

### PR DESCRIPTION
**Pull request by carolinegreen**
Update schemas for both DOS specialists and DOS labs.  Joint commit with @carolinegreen and @pcraig3

### CODE REVIEW

**Comment by pcraig3** [comment]
:+1:

**Comment by carolinegreen** [comment]
Not sure you can thumbs up a joint commit you're part of?

**Comment by TheDoubleK** [comment]
:+1: 

With a caveat that we will need to tell all testers that they need to delete their Labs lot and start again, as any saved labs will have a max price in and so won't validate.

**Comment by pcraig3** [comment]
Ooh, good point.  I'll remove them from preview/staging.

**Comment by TheDoubleK** [comment]
Remove what - labs for all users?

**Pull request merged**
