### PR TITLE
hypothesis example_listings: add max_size to availability and *Requirements strings

### PR DESCRIPTION
**Pull request by risicle**
sizes corresponding to size limits in json schemas. this should stop sporadic test failures.

cc @andrewchong, @allait (original author)

Also wondering if I should:
- expand the `alphabet` a bit to include spaces and possibly even some odd unicode characters.
- make `location` actually output one of the locations from the schema - I'm not sure how it validates with just some random strings...

### CODE REVIEW

**Comment by TheDoubleK** [comment]
Is there a possibility that adding spaces to the dictionary could introduce more intermittent test failures if they happened to push things over a word limit in the schema?  Some unicode characters might not be a bad thing though.

**Comment by risicle** [comment]
Ah yes word limit good point

**Comment by risicle** [comment]
@TheDoubleK I've got around the word count problem by using hypothesis' `.filter()` feature.

**Comment by TheDoubleK** [comment]
Looks good, tests still pass :)
I'm not 100% sure how these are used in the test suite, but clearly the location must never matched "for real".
:+1:

**Pull request merged**
