### PR TITLE
Fix DOS schema enum values

### PR DESCRIPTION
**Pull request by robyoung**
This is the API side of https://github.com/alphagov/digitalmarketplace-frameworks/pull/192

Existing brief data will need to be deleted or updated.

### CODE REVIEW

**Comment by TheDoubleK** [comment]
Does this mean that in future we have the potential to change the labels but keep the same value so things don't all break (e.g. changes in capitalisation, hyphenation, etc.)?  Living the dream!

**Comment by TheDoubleK** [comment]
Of course, in that case there is the potential for us to be storing values that don't reflect the answer provided... e.g. like if we change a label from "Scotland" to "Wales" we would have 'scotland' stored for people who ticked the "Wales" box :/

**Comment by TheDoubleK** [comment]
Anyway, these metaphysical questions aside, :+1: for the changes here - we need them.

**Comment by robyoung** [comment]
Yes, and yes, it may contain it's own set of pain, but we'll at least be able to decouple the two.

**Pull request merged**
