### PR TITLE
set_a_declaration view: add handling of PATCH method 

### PR DESCRIPTION
**Pull request by risicle**
https://trello.com/c/rMwWZyBv

This PR also safens-up a couple of existing views by taking row locks where appropriate and reduces the amount of unnecessary eager loading that's taking place. Also refactored tests for this view which were previously covering only a subset of its functionality.

This shouldn't go anywhere near merging until https://trello.com/c/X4vuC79J has been dealt with satisfactorily.

### CODE REVIEW

**Comment by risicle** [comment]
> There are a couple of test class bases that aren't used (leftover from a refactor?)

Um, no? If there are it's probably a mistake.

**Comment by katstevens** [comment]
Oh. I meant `TestSetSupplierDeclarationsBasicPatch` and `TestSetSupplierDeclarationsBasicPut` -  I can't see where they're used?

**Comment by risicle** [comment]
Ah - they're actual tests - they use `JSONUpdateTestMixin` which is something I didn't know about before. Was looking at the tests in them and thought it would be good if I found a way to ensure none of their calls wrote to the db. Mocked out `.commit()` or something? Dunno.

**Comment by risicle** [comment]
I've pushed some commits which add a hacky explicit self re-assignment of the declaration simply to ensure the validators are run until we can get https://trello.com/c/X4vuC79J sorted

**Pull request merged**
