### PR TITLE
Tiny alteration to accommodate installation on debian jessie

### PR DESCRIPTION
**Pull request by risicle**

### CODE REVIEW

**Comment by allait** [comment]
Can we just add this to the normal `README` instead of adding a new file?

**Comment by risicle** [comment]
Yup sure, just wanted to keep my oddness out the way seeing that it might only ever be relevant to me.... will re-spin later.

**Comment by TheDoubleK** [comment]
:+1:

**Comment by risicle** [comment]
I can't merge this as I'm not a member of the organization yet.

**Comment by risicle** [comment]
(tadaa)

**Pull request merged**
