### PR TITLE
Update requirements-dev

### PR DESCRIPTION
**Pull request by lfdebrux**
Bumps updated dependencies in `requirements-dev.txt`.

### CODE REVIEW

**Comment by jonodrew** [comment]
The error is the same on you helped me fix last week - we had to reorder the file: https://github.com/alphagov/digitalmarketplace-utils/pull/490/commits/368e50fb5396749076eba28505cb45c5d6642efb

**Comment by lfdebrux** [comment]
> The error is the same on you helped me fix last week - we had to reorder the file: [alphagov/digitalmarketplace-utils@368e50f](https://github.com/alphagov/digitalmarketplace-utils/commit/368e50fb5396749076eba28505cb45c5d6642efb)

Ah yes that makes sense, thanks

**Comment by lfdebrux** [comment]
> > The error is the same on you helped me fix last week - we had to reorder the file: [alphagov/digitalmarketplace-utils@368e50f](https://github.com/alphagov/digitalmarketplace-utils/commit/368e50fb5396749076eba28505cb45c5d6642efb)
> 
> Ah yes that makes sense, thanks

I actually decided to fix this a different way, which I think will be more sustainable; adding the `-U` flag to `pip` for `make requirements-dev` makes sure we get the latest valid version of sub-dependencies.

Any objections @jonodrew, @risicle?

**Comment by jonodrew** [comment]
> > > The error is the same on you helped me fix last week - we had to reorder the file: [alphagov/digitalmarketplace-utils@368e50f](https://github.com/alphagov/digitalmarketplace-utils/commit/368e50fb5396749076eba28505cb45c5d6642efb)
> > 
> > 
> > Ah yes that makes sense, thanks
> 
> I actually decided to fix this a different way, which I think will be more sustainable; adding the `-U` flag to `pip` for `make requirements-dev` makes sure we get the latest valid version of sub-dependencies.
> 
> Any objections @jonodrew, @risicle?

None from me

**Comment by risicle** [comment]
Yeah I think that seems like the least wrong way of doing it. Or rather - it's one of those things that seems like pip should be doing by default, so let's force it.

**Comment by risicle** [comment]
FWIW we do have across the project a number of places with regexes not using raw strings - I fix them where I find them, but I'm sure there are more lurking.

**Pull request merged**
