### PR TITLE
Add new statuses to frameworks

### PR DESCRIPTION
**Pull request by quis**
### coming ⇢ open ⇢ pending ⇢ standstill ⇢ live ⇢ expired

--

- "coming" replaces "pending" as the state before a framework is open for suppliers to make their applications
- "pending" moves in the order to reflect that it is the stage between a supplier applying and CCS telling suppliers if they're successful
- "standstill" is a new state which is in between suppliers being told if they're successful and their services being live on the marketplace

### CODE REVIEW

**Comment by TheDoubleK** [comment]
Requires an update to the status enum - see here for something to copy & paste: https://github.com/alphagov/digitalmarketplace-api/blob/master/migrations/versions/100_add_open_status.py

**Comment by allait** [comment]
I'd suggest getting rid of that enum and replace it with model validator similar to https://github.com/alphagov/digitalmarketplace-api/blob/master/app/models.py#L416-L421. That would still require a migration but at least we won't need to do this each time we want to add/remove/rename a status in the future. I don't think the safety provided by enums is worth the migrations issues and `@validators` error message can be much nicer than the database error we get from invalid enum values.

**Comment by robyoung** [comment]
We discussed how we should go about adding or updating a framework now that the validation isn't in the database. It would be good to add that to the README or a script.

**Comment by quis** [comment]
:+1: to the endpoint

**Comment by robyoung** [comment]
:+1: to the rest

**Pull request merged**
