### PR TITLE
Bump digitalmarketplace-utils dependency to v46.1.2, update misc other dependencies

### PR DESCRIPTION
**Pull request by risicle**
This is non-essential but should bring in the improved `/_status` logging noted as a problem in https://trello.com/c/CqTPp8E0

### CODE REVIEW

**Comment by risicle** [comment]
Interesting that it's failing the snyk test - the issue that snyk is citing *actually* appears to apply to *all* 1.2 versions of sqlalchemy, but they've got it in their db as 1.2.17+

**Comment by risicle** [comment]
(I've dropped them a note about it)

**Comment by risicle** [comment]
Think I should "ignore" that vuln for now?

**Comment by katstevens** [comment]
If we're already vulnerable then ignoring would leave us no worse off?

**Comment by risicle** [comment]
The vulnerability is a bit of a "sqlalchemy lets you shoot yourself in the foot" vulnerability, and I don't think we use the functionality that is vulnerable. There is a fix merged to master but it hasn't made it to a release yet.

**Pull request merged**
