### PR TITLE
Add buyer domains: wandle, iwm, bl

### PR DESCRIPTION
**Pull request by benvand**

### CODE REVIEW

**Comment by idavidmcdonald** [comment]
Do we not do these in the database now?

**Comment by risicle** [comment]
Should this file still exist then if that's the case? Otherwise it's just confusing.

**Comment by katstevens** [comment]
Ah that's my fault for not tidying up after myself! Now the DB table etc has been deployed to prod, we can get rid of the file (the data migration should happily skip the missing file if we have to roll forward/backward for whatever reason). There's a little bit of untangling to do as well as just deleting the file, I'm happy to do a quick PR now.

**Comment by benvand** [comment]
Done these using the api! Thanks @katstevens !

**Comment by katstevens** [comment]
That PR: https://github.com/alphagov/digitalmarketplace-api/pull/683

**Pull request closed without merging**
